### ISSUE TITLE
strange php segfault

### ISSUE THREAD

**Issue by DraconPern** [cryptoapi/Bitcoin-Payments-Woocommerce#1]
With this plugin activated, viewing orders causes segfault.  for example, /wp-admin/post.php?post=2&action=edit

This is on latest amazon Linux, php56-5.6.32, httpd24-2.4.27, woocommerce 3.2.6, Aelia Currency Switcher for WooCommerce 3.9.3.160202

Deactivating this plugin fixes the crash.  Everything else seems to work.

**Comment by DraconPern** [comment]
For currency, I only used cryptocurrency bitcoin (w/o conversion).

**Comment by cryptoapi** [comment]
No other users reported problem. Please retest on new server with fresh wordpress installation.
