### ISSUE TITLE
you will not use blockchain adress, why ?

### ISSUE THREAD

**Issue by mr0Ot** [cryptoapi/Bitcoin-Payments-Woocommerce#3]
You will not you bitcoin adress from blockchain why?
that is not stupid that is bullshit!

it is a joke.
now i will search for a good programmer that make it better!
a free plugin for wordpress with a plugin who every can use it!
nobody must use your fucking website for this.

your payments gateway is a joke!

**Comment by cryptoapi** [comment]
We use directly bitcoin daemon/blockchain without third party API.
