### ISSUE TITLE
Cannot receive exchange rates from xe.com

### ISSUE THREAD

**Issue by poopaapoopaa** [cryptoapi/Bitcoin-Payments-Woocommerce#5]
On checkout page, I get 

> Sorry, but there was an error processing your order. Please try later or use a different payment method. System cannot receive exchange rates for EUR/USD from xe.com

I saw a similar error was mentioned here: https://wordpress.org/support/topic/system-cannot-receive-exchange-rates-for-eur-usd-from-google-finance-4/

My plugin is updated though, the link in my gourl.php already uses "https".

**Comment by getorca** [comment]
Looks like XE just pushed a release to stop people/plugins from scraping from the UI, the CURL call now returns an empty container where the content should be.

**Comment by poopaapoopaa** [comment]
I see. Any alternative source? by the way, I don't see why we always need to convert to USD first when places such as bitfinex quote the direct rates of BTCEUR, BTCGBP, BTCJPY etc.

**Comment by cryptoapi** [comment]
We added currency exchange sources to plugin -
http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
http://currencyconverterapi.com/
https://www.bitstamp.net/api/ticker/
https://blockchain.info/ticker
